# Configure file for MCDReforgedPluginManager


# The minimum permission level to use MPM commands
# 使用 MCDReforgedPluginManager 指令的最低权限
permission: 4

# The source of plugin catalogue to fetch data
# 插件仓库数据源
# Options 选项:
# - https://raw.githubusercontent.com/MCDReforged/PluginCatalogue/meta
# - https://cdn.jsdelivr.net/gh/MCDReforged/PluginCatalogue@meta
source: https://cdn.jsdelivr.net/gh/MCDReforged/PluginCatalogue@meta

# The timeout for network requests
# 网络请求的超时时间
timeout: 5

# The time interval between each cache (unit: minute)
# 定时更新插件索引的时间间隔（单位：分钟）
cache_interval: 2

# If set to true, the plugin will check plugin updates after each scheduled cache
# 若设为 true，插件将在每次定时更新插件索引后自动检查更新
check_update: true


# The path to install the plugin, should be one of the value of 'plugin_directories' of the MCDR config
# 安装插件的位置，应是 MCDR 配置中的 'plugin_directories' 中的一个
install_path: plugins
