# Configure file for MCDReforgedPluginManager


# The minimum permission level to use MPM commands
# 使用 MCDReforgedPluginManager 指令的最低权限
permission: 4

# The source of plugin catalogue to fetch data, should be the url to download the whole meta branch
# 插件仓库数据源，应是下载整个 meta 分支的链接
source: https://github.com/MCDReforged/PluginCatalogue/archive/refs/heads/meta.zip

# The timeout for network requests
# 网络请求的超时时间
timeout: 5

# The time interval between each cache (unit: minute)
# 定时更新插件索引的时间间隔（单位：分钟）
cache_interval: 2

# If set to true, the plugin will check plugin updates after each scheduled cache
# 若设为 true，插件将在每次定时更新插件索引后自动检查更新
check_update: true

# The path to install the plugin, should be one of the value of 'plugin_directories' of the MCDR config
# 安装插件的位置，应是 MCDR 配置中的 'plugin_directories' 中的一个
install_path: plugins

# The url template used when downloading GitHub release assets, where '{url}' will be replaced with the actual url
# Example using ghproxy: https://ghproxy.com/{url}, the download url will be https://ghproxy.com/https://github.com/user/repo/releases/download/...
# 在下载 GitHub 发布素材时使用的 url 模版，'{url}' 将被替换为实际的 url
# 使用 ghproxy 的例子: https://ghproxy.com/{url}，实际下载 url 将被替换为 https://ghproxy.com/https://github.com/user/repo/releases/download/...
release_download_url_template: '{url}'

# Proxy addresses, both http and https is optional
# 代理地址，http 与 https 都是可选的
proxy:
  http:
  https:
